import React from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { Download, Share2, ArrowRight, RefreshCcw } from 'lucide-react';
import { motion } from 'framer-motion';

interface ResultDisplayProps {
    imageUrl: string;
    onReset: () => void;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ imageUrl, onReset }) => {
    // In a real app, this would be a permanent URL to the image hosted on a CDN
    // Since we are using base64 for the demo, we use a placeholder for the QR code 
    // to avoid the "Data too long" error.
    const qrPlaceholderUrl = "https://petra.ai/booth-preview";

    const handleDownload = () => {
        const link = document.createElement('a');
        link.href = imageUrl;
        link.download = `petra-ai-moment-${Date.now()}.jpg`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    return (
        <div className="flex flex-col lg:flex-row items-center justify-center gap-12 w-full max-w-6xl mx-auto px-6">
            {/* Generated Image */}
            <motion.div
                initial={{ opacity: 0, x: -50 }}
                animate={{ opacity: 1, x: 0 }}
                className="relative w-full max-w-md aspect-square bg-slate-100 rounded-[3rem] overflow-hidden shadow-2xl border-8 border-white"
            >
                <img
                    src={imageUrl}
                    alt="Generated Petra Moment"
                    className="w-full h-full object-cover"
                />
                <div className="absolute top-6 left-6 bg-white/30 backdrop-blur-md px-4 py-2 rounded-full border border-white/40">
                    <span className="text-white font-bold text-sm tracking-widest uppercase">Petra AI</span>
                </div>
            </motion.div>

            {/* Actions & QR */}
            <motion.div
                initial={{ opacity: 0, x: 50 }}
                animate={{ opacity: 1, x: 0 }}
                className="flex flex-col gap-8 items-center lg:items-start text-center lg:text-left"
            >
                <div className="space-y-4">
                    <h2 className="text-5xl font-extrabold text-[#171739] leading-tight">
                        Your Petra <br /> <span className="text-[#FFD447]">Moment is ready!</span>
                    </h2>
                    <p className="text-slate-500 text-xl max-w-md">
                        Scan the QR code to see how you can adopt your new buddy.
                    </p>
                </div>

                <div className="flex flex-col sm:flex-row items-center gap-8 bg-slate-50 p-8 rounded-[2.5rem] border-2 border-slate-100">
                    <div className="bg-white p-4 rounded-3xl shadow-lg border-2 border-[#FFD447]/30">
                        <QRCodeSVG value={qrPlaceholderUrl} size={160} level="H" includeMargin={false} />
                    </div>
                    <div className="flex flex-col gap-4 w-full sm:w-auto">
                        <button
                            onClick={handleDownload}
                            className="flex items-center justify-center gap-3 bg-[#171739] text-white px-8 py-5 rounded-2xl font-bold text-lg hover:bg-[#252756] transition-all active:scale-95"
                        >
                            <Download size={24} className="text-[#FFD447]" /> Download Photo
                        </button>
                        <button className="flex items-center justify-center gap-3 bg-white text-[#171739] border-2 border-slate-200 px-8 py-5 rounded-2xl font-bold text-lg hover:bg-slate-50 transition-all active:scale-95">
                            <Share2 size={24} /> Share
                        </button>
                    </div>
                </div>

                <button
                    onClick={onReset}
                    className="flex items-center gap-3 text-slate-400 hover:text-[#171739] font-bold text-lg group transition-all"
                >
                    <RefreshCcw className="group-hover:rotate-180 transition-transform duration-500 text-[#FFD447]" />
                    Start Fresh
                </button>

                <p className="text-slate-400 text-sm mt-4 italic">
                    AI-generated image for demo purposes. Generated by Petra.
                </p>
            </motion.div>
        </div>
    );
};

export default ResultDisplay;
